name: oncue

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/oncue_development
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle-data:/usr/local/bundle
    user: "1000:1000"
    tty: true

volumes:
  bundle-data:
  db-data:
