# syntax=docker/dockerfile:1

# Make sure RUBY_VERSION matches the version in .ruby-version and BUNDLER_VERSION matches the version in Gemfile.lock
ARG RUBY_VERSION=3.4.4
ARG BUNDLER_VERSION=2.6.9

FROM ruby:$RUBY_VERSION

# Rails app lives here
WORKDIR /rails

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v "${BUNDLER_VERSION}" && bundle install

# Copy application code
COPY . .

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint.dev"]

# Start server via bin/dev, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/dev"]
