# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.4
ARG BUNDLER_VERSION=2.6.9

FROM ruby:$RUBY_VERSION

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v "${BUNDLER_VERSION}" && bundle install

COPY . .

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint.dev"]
